import * as Adaper from "./adapter.ts";

type Manifest = {
        indentType: "tab" | "spaces",
        indentSize: 2 | 4 | 8,
        username?: string,
        projectSlug?: string,
        projectSecretCode?: string
};

let manifestFile: Adaper.FileContext;
export const path = "assets/__editor.json";

export let manifestData: Manifest;

const important = Object.freeze([
        "This file and its contents are generated by the editor plugin",
        "It contains save data about project settings. Please don't",
        "move/rename/edit/delete it unless you know what you are doing.",
        "This file dosen't affect your project when you run it."
] as const);

export async function saveManifest() {
        const indentation = manifestData.indentType === "tab" ? "\t" : " ".repeat(manifestData.indentSize);
        const content = JSON.stringify({important, ...manifestData}, null, indentation);
        await manifestFile.writeContent(content);
}

export async function initialize(pluginInterface: Adaper.PluginInterface) {
        manifestFile = (await Adaper.createFile(pluginInterface, path))!;
        manifestData = {
                indentType: "spaces",
                indentSize: 2
        };

        if (!manifestFile.exists) {
                await saveManifest();
                return;
        }

        const manifestText = await manifestFile.readContent();
        const manifestContent = JSON.parse(manifestText! as string);

        const indentType = manifestContent["indentType"];
        if (indentType === "tab" || indentType === "spaces") {
                manifestData.indentType = indentType;
        }

        const indentSize = manifestContent["indentSize"];
        if (indentSize === 2 || indentSize === 4 || indentSize === 8) {
                manifestData.indentSize = indentSize;
        }

        const username = manifestContent["username"];
        if (typeof username === "string" && username.trim() !== "") {
                manifestData.username = username;
        }

        const projectSlug = manifestContent["projectSlug"];
        // TODO: More checks can be applied here to make sure it is at least a valid part inside a link
        if (typeof projectSlug === "string" && projectSlug.trim() !== "") {
                manifestData.projectSlug = projectSlug;
        }

        const projectSecretCode = manifestContent["projectSecretCode"];
        // TODO: More checks can be applied here to make sure it is at least a valid secret code
        if (typeof projectSecretCode === "string" && projectSecretCode.length === 8) {
                manifestData.projectSecretCode = projectSecretCode;
        }

        await saveManifest();
}