import * as Adaper from "./adapter.ts";

type Manifest = {
        indentType: "tab" | "spaces",
        indentSize: 2 | 4 | 8,
        username?: string,
        projectSlug?: string,
        projectSecretCode?: string
};

let manifestData: Manifest = {
        indentType: "tab",
        indentSize: 2
};

let manifestFile: Adaper.FileContext;
export const path = "assets/__editor.json";

type ChangeListener<ChangedKey extends keyof Manifest> = (value: Manifest[ChangedKey]) => void;
const changeListeners: {[ChangedKey in keyof Manifest]?: Set<ChangeListener<ChangedKey>>} = {};

export type ChangeListenerController = {
        trigger: () => void;
        remove: () => void;
};

export function registerChangeListener<ChangedKey extends keyof Manifest>(key: ChangedKey, changeListener: ChangeListener<ChangedKey>): ChangeListenerController {
        const keyChangeListeners = changeListeners[key] ?? new Set<ChangeListener<ChangedKey>>();
        changeListeners[key] = keyChangeListeners as Set<any>;

        keyChangeListeners.add(changeListener);

        return Object.freeze({
                trigger: () => {
                        changeListener(manifestData[key]);
                },
                remove: () => {
                        keyChangeListeners.delete(changeListener);
                }
        } as const);
}

function applyManifestValue<ChangedKey extends keyof Manifest>(key: ChangedKey, value: Manifest[ChangedKey]) {
        if (Object.is(manifestData[key], value)) {
                return false;
        }

        manifestData[key] = value;

        const keyChangeListeners = changeListeners[key] as Set<ChangeListener<ChangedKey>> | undefined;
        if (keyChangeListeners === undefined) {
                return true;
        }

        for (const keyChangeListener of keyChangeListeners) {
                keyChangeListener(value);
        }

        return true;
}

const important = Object.freeze([
        "This file and its contents are generated by the editor plugin",
        "It contains save data about project settings. Please don't",
        "move/rename/edit/delete it unless you know what you are doing.",
        "This file dosen't affect your project when you run it."
] as const);

export async function setManifestValue<ChangedKey extends keyof Manifest>(key: ChangedKey, value: Manifest[ChangedKey]) {
        if (!applyManifestValue(key, value)) {
                return;
        }

        await manifestFile.writeContent({important, ...manifestData});
}

export async function setManifestValues(values: Partial<Manifest>) {
        let shouldSave = false;

        for (const key in values) {
                const typedKey = key as keyof Manifest;
                if (values[typedKey] === undefined) {
                        continue;
                }

                if (applyManifestValue(typedKey, values[typedKey] as Manifest[typeof typedKey])) {
                        shouldSave = true;
                }
        }

        if (!shouldSave) {
                return;
        }

        await manifestFile.writeContent({important, ...manifestData});
}

export async function initialize(pluginInterface: Adaper.PluginInterface) {
        manifestFile = (await Adaper.createFile(pluginInterface, path))!;
        if (!manifestFile.exists) {
                await setManifestValues(manifestData);
                return;
        }

        const manifestContent = await manifestFile.readContent();
        if (typeof manifestContent !== "object") {
                await setManifestValues(manifestData);
                return;
        }

        const savedManifestData = {...manifestData};
        const manifestRecord = manifestContent as Record<string, unknown>;

        const indentType = manifestRecord["indentType"];
        if (indentType === "tab" || indentType === "spaces") {
                savedManifestData.indentType = indentType;
        }

        const indentSize = manifestRecord["indentSize"];
        if (indentSize === 2 || indentSize === 4 || indentSize === 8) {
                savedManifestData.indentSize = indentSize;
        }

        const username = manifestRecord["username"];
        if (typeof username === "string" && username.trim() !== "") {
                savedManifestData.username = username;
        }

        const projectSlug = manifestRecord["projectSlug"];
        // TODO: More checks can be applied here to make sure it is at least a valid part inside a link
        if (typeof projectSlug === "string" && projectSlug.trim() !== "") {
                savedManifestData.projectSlug = projectSlug;
        }

        const projectSecretCode = manifestRecord["projectSecretCode"];
        // TODO: More checks can be applied here to make sure it is at least a valid secret code
        if (typeof projectSecretCode === "string" && projectSecretCode.length === 8) {
                savedManifestData.projectSecretCode = projectSecretCode;
        }

        await setManifestValues(savedManifestData);
}